//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int Money { get; set; }
        public int Level { get; set; }
        public int Health { get; set; }
        public int Boredom { get; set; }
        public bool Alive { get; set; }
        public Nullable<int> Room { get; set; }
    
        public virtual Room Room1 { get; set; }
    }
}
